### ISSUE TITLE
Persistent Stopping Player message after selecting Restart

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#50] opened 2015-12-23 22:44 UTC
**How to Duplicate**
Install 356#artifacts
Select Stop command
Select Restart command
See 15.10 (http://g.recordit.co/Q4WNqzv8Rt.gif) and 14.04 (http://g.recordit.co/ED5X6Wttyl.gif)

**Expected**
1. No persistent pop up "Stopping Rise Vision Player" after stopping the Player

**Environment**
Ubuntu 14.04 and 15.10 64bit

**Comment by fjvallarino** [comment] 2015-12-24 23:20
@lapinnoir @tejohnso By design these notification bubbles ignore the timeout parameter provided to them, so they will show for about 10 seconds. Maybe we can leave the first message "Stopping..." and remove the second "...stopped".

https://bugs.launchpad.net/ubuntu/+source/notify-osd/+bug/390508

**Comment by lapinnoir** [comment] 2015-12-24 23:35
@fjvallarino @tejohnso 
Ok. Yes I was expecting the 'Stopped' message as indicator that Player has stopped, at least in the UI, before I do something else.

**Comment by tejohnso** [comment] 2015-12-25 16:13
Closing this one - to address as part of #54

**Closed by tejohnso** 2015-12-25 16:13 UTC
